### PR TITLE
Fixes sampling from multi-agent observation space

### PR DESCRIPTION
**Pull request by semitable**

### CODE REVIEW

**Comment by koulanurag** [comment]
Hi @semitable,
Thanks for this pull request.

However, Let's begin by raising an issue with sample code to show the error(or problem).  This will help in documenting this pull request.

And, Then I would be happy to merge it.

- Anurag Koul

**Comment by semitable** [comment]
Hi @koulanurag 
I did raise an issue with some sample code that currently fails. There are no test cases for the action/state spaces atm, so I am not sure how you want to approach this.

**Comment by koulanurag** [comment]
Hi, Thanks for raising the issue.

It's much clear now how to replicate this issue.

Let's add an assertion in `test_observation_space` for each test file.
https://github.com/koulanurag/ma-gym/blob/master/tests/envs/test_checkers.py#L91

It could be something like:
```
assert env.observation_space.contains(env.observation_space.sample())
```

**Comment by semitable** [comment]
Simple enough, agreed. I added the test changes to the PR

**Pull request merged**
